apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metagpu-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: "metagpu-exporter"
    cnvrg-infra-prometheus: cnvrg-infra-cnvrg
spec:
  selector:
    matchLabels:
      app: "metagpu-exporter"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: "15s"